chore: remove openssl from the dependency tree.

diff --git a/.github/workflows/toml.yaml b/.github/workflows/toml.yaml
--- a/.github/workflows/toml.yaml
+++ b/.github/workflows/toml.yaml
@@ -41,3 +41,7 @@ jobs:
 
       - name: Check for unused dependencies
         run: cargo +nightly udeps --all-targets --all-features
+
+      # Use cargo tree, and fail if openssl is present
+      - name: Check openssl
+        run: cargo tree --edges no-dev --all-features | grep openssl && exit 1 || exit 0
